### ISSUE TITLE
발주 내역 출력 에러

### ISSUE THREAD

**Issue by gunny97h** [dckat/jdbc-pjt1-wms#3]
문제 설명

발주 내역을 Swing으로 받아오는 과정에서 오류 발생

![image](https://github.com/user-attachments/assets/fffc8f4f-dbb1-4c8e-b604-7ceac1fae68c)
```
> Task :com.ssginc.wms.supply.Main.main()
[SupplyProductVO(supply_id=10, product_id=1, product_name=Smartphone, category_name=Electronics, supply_price=400, supply_amount=222, supply_time=2024-12-02T09:19:27), SupplyProductVO(supply_id=9, product_id=1, product_name=Smartphone, category_name=Electronics, supply_price=400, supply_amount=100, supply_time=2024-12-02T09:19:10), SupplyProductVO(supply_id=8, product_id=3, product_name=Novel, category_name=Books, supply_price=8, supply_amount=555, supply_time=2024-12-01T09:12:57), SupplyProductVO(supply_id=7, product_id=5, product_name=Tennis Racket, category_name=Sports & Outdoors, supply_price=50, supply_amount=222, supply_time=2024-12-01T09:09:39), SupplyProductVO(supply_id=6, product_id=4, product_name=Garden Chair, category_name=Home & Garden, supply_price=30, supply_amount=100, supply_time=2024-11-29T15:11:02), SupplyProductVO(supply_id=5, product_id=5, product_name=Tennis Racket, category_name=Sports & Outdoors, supply_price=50, supply_amount=30, supply_time=2024-11-25T13:00), SupplyProductVO(supply_id=4, product_id=4, product_name=Garden Chair, category_name=Home & Garden, supply_price=30, supply_amount=25, supply_time=2024-11-18T12:00), SupplyProductVO(supply_id=3, product_id=3, product_name=Novel, category_name=Books, supply_price=8, supply_amount=75, supply_time=2024-11-05T11:00), SupplyProductVO(supply_id=2, product_id=2, product_name=T-shirt, category_name=Clothing, supply_price=10, supply_amount=100, supply_time=2024-10-28T10:00), SupplyProductVO(supply_id=1, product_id=1, product_name=Smartphone, category_name=Electronics, supply_price=400, supply_amount=50, supply_time=2024-10-15T09:00)]
jtable 추가
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.base/java.text.DateFormat.format(DateFormat.java:342)
	at java.base/java.text.Format.format(Format.java:159)
	at java.desktop/javax.swing.JTable$DateRenderer.setValue(JTable.java:5441)
	at java.desktop/javax.swing.table.DefaultTableCellRenderer.getTableCellRendererComponent(DefaultTableCellRenderer.java:262)
	at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5797)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2210)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2112)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1908)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:842)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1105)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3959)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:890)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

발생 조건

![image](https://github.com/user-attachments/assets/65bca685-1ec9-48dd-b286-c887efe645f6)
![image](https://github.com/user-attachments/assets/a0f0bc37-3c25-49eb-b031-0d5f3c00f898)
list를 출력해보면 정상 출력 

![image](https://github.com/user-attachments/assets/3031cff5-65f7-4009-896b-808a2f51793d)
![image](https://github.com/user-attachments/assets/93523dd8-5d01-4822-9ab7-30108a25de12)
"jtable 추가" 메세지도 정상 출력

--> 데이터를 가져오는 과정에서는 문제 없음 

Supply_time을 tableModel에 추가하는 과정을 주석 처리할 시 정상 작동
![image](https://github.com/user-attachments/assets/b58f693a-aaa5-45fe-9569-8b1b02bb3cde)
![image](https://github.com/user-attachments/assets/7e650a3e-bc2e-443d-9ce2-7e965ede6470)

기대 결과

Supply_time이 정상적으로 출력되어야 함.

**Comment by dckat** [comment]
<img width="927" alt="스크린샷 2024-12-02 오후 2 01 45" src="https://github.com/user-attachments/assets/fa01479d-65b8-4cc4-8888-760dd03d0fc5">

- 이 부분에서 Java 내에서는 LocalDateTime으로 표현이 되어야 하는데, TimeStamp로 표현이 되어 발주시간이 표현되지 않는거 같습니다. 빨간 박스 내부의 코드를 다음과 같이 수정해주세요
```
return LocalDateTime.class;
```

**Comment by newbackjava** [comment]
네 새롭게 생성된 ui관련 객체는 상위 컨테이너에 삽입해주고
그래도 나타나지 않을 시에는
해당 패널을 리로딩해주는 방식으로 해결합니다.
